# Generated by Django 4.2.13 on 2024-06-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.AlterField(
            model_name='freequote',
            name='select_service',
            field=models.CharField(choices=[('Business Consultancy', 'Business Consultancy'), ('Certification', 'Certification'), ('Government Grants', 'Government Grants'), ('Funding', 'Funding')], max_length=50, verbose_name='Selected Service'),
        ),
    ]
