# Generated by Django 4.2.13 on 2024-06-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_app', '0002_subscribe_alter_freequote_select_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default=1, max_length=20, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
